### ISSUE TITLE
Add Abandoned type to TransitionState enum

### ISSUE THREAD

**Issue by andreev-io** [andreev-io/little-raft#13]
Raft is an asynchronous protocol, so one of the challenges when using it is getting feedback on whether a particular transition has or hasn't been applied. To solve this problem, Little Raft calls the user-defined `register_transition_state` hook every time any transition changes its state. This way the library user can keep track of transitions as they move through the `Queued -> Committed -> Applied` pipeline.

However, a transition could be ignored by the replica it has been submitted to. The most likely reason for that is because the replica is not the cluster leader. Another possible reason is that the replica used to be the leader, then got disconnected from the rest of the cluster, kept accepting transitions for processing for a while and then had to drop them when connecting back to the cluster that in the meanwhile elected another, newer leader (the stale leader dropping uncommitted transitions is the desired behavior in this case).

To let the user know when a transition got dropped, we should add `Abandoned` state to the `TransitionState` enum. We could also have that `Abandoned` state wrap around another type so that we could signal the particular reason why a transition has been abandoned -- `NotLeader` vs `UncommittedUnsynced`. Naming could be improved.

**Comment by andreev-io** [comment]
@paulhenri Want me to assign this to you?

**Comment by paulhenri** [comment]
Yes please :)

Le sam. 28 août 2021 à 11:05, Ilya Andreev ***@***.***> a
écrit :
