### ISSUE TITLE
Extend TransitionAbandonedReason enum

### ISSUE THREAD

**Issue by andreev-io** [andreev-io/little-raft#34]
Currently the enum is 
```
pub enum TransitionAbandonedReason {
    // NotLeader transitions have been abandoned because the replica is not
    // the cluster leader.
    NotLeader,
}
```

However, transitions can also be dropped by a replica if at some point it gets disconnected from majority of the cluster thinking it is still a leader accepting transitions; upon reconnecting to the rest of the cluster, such a replica will drop uncommitted transitions due to a discrepancy with consensus achieved by the cluster majority.

**Comment by andreev-io** [comment]
See also https://github.com/andreev-io/little-raft/issues/13.

**Comment by suzaku** [comment]
Which part of the source code should I look into?

**Comment by andreev-io** [comment]
@suzaku The only place where follower Replicas might overwrite uncommitted transitions is here: https://github.com/andreev-io/little-raft/blob/master/little_raft/src/replica.rs#L537-L547. When the log vector is truncated, transitions get abandoned.

**Comment by andreev-io** [comment]
@suzaku I assigned this to you. Hope you don't mind. 😄

**Comment by andreev-io** [comment]
By the way, in the paper, this behavior is documented in section 5.3. https://raft.github.io/raft.pdf. Also see the highlighted text in the screenshot below.

![image](https://user-images.githubusercontent.com/18560147/146668748-8b69d8c8-d1fc-4526-8958-c436366820ed.png)

**Comment by suzaku** [comment]
I will take a look. The change seems straight forward enough, but I'll read the paper for the rationale behind the change for sure. I've forgotten most of the details about Raft.
